[package]
name = "rusty-broom"
version = "0.1.1"
edition = "2024"
description = "Reclaim disk space from build artifacts of projects you stopped working on"
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/oriontvv/rusty-broom/"
repository = "https://github.com/oriontvv/rusty-broom/"
keywords = ["tui", "cli", "cleaner", "disk", "usage"]
categories = ["command-line-utilities"]


[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
dirs = "7.0.0"
ratatui = "0.30.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.5"

[profile.release]
lto = "thin"
strip = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ version }/{ name }-linux-musl{ archive-suffix }"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/{ version }/{ name }-win{ archive-suffix }"

[package.metadata.binstall.overrides.aarch64-apple-darwin]
pkg-url = "{ repo }/releases/download/{ version }/{ name }-mac{ archive-suffix }"